version: "3.8"
services:
  redis:
    image: redis:6.2.6-alpine3.15
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  consumer:
    build:
      context: .
    environment:
      - SPRING_REDIS_HOST=redis

volumes:
  redis_data: